name: SSH Tunnel
on: push
#---
jobs:
  deploy:
    name: Set up tunnel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup tunnel
      uses: pantov/test3@main
      with:
        timeout: 5h
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        ngrok_token: ${{ secrets.NGROK_TOKEN }}
