name: SSH Tunnel
on: push
#---
jobs:
  deploy:
    name: Set up tunnel
    runs-on: centos-7
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup tunnel
      uses: pantov/ssh-tunnel-action@main
      with:
        timeout: 2h
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        ngrok_token: ${{ secrets.NGROK_TOKEN }}
